#!/bin/zsh

js_files=( node_modules/twojs-browserify/two.clean.js )
css_dir=resources/public/css

browserify $js_files -o resources/public/js/deps.js

[[ ! ( -d  $css_dir ) ]] && mkdir $css_dir
cp -f node_modules/purecss/build/pure.css $css_dir
